### ISSUE TITLE
Fatal error: Cannot call method 'send' of null

### ISSUE THREAD

**Issue by Rowno** [mklabs/tiny-lr#25] opened 2013-10-17 22:18 UTC
I'm randomly getting a `Fatal error: Cannot call method 'send' of null` error quite often which crashes Grunt (using this through `grunt-contrib-watch`).

I'm running Grunt on Windows 7 and I'm using the [Rearm](https://chrome.google.com/webstore/detail/rearm/omgokhmgebbnldchkfienblhhjlmjdlm) Chrome extension.

```
Fatal error: Cannot call method 'send' of null
C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\client.js:74
  this.ws.send(JSON.stringify(data));
          ^
TypeError: Cannot call method 'send' of null
    at Client.send (C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\client.js:74:11)
    at Client.<anonymous> (C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\client.js:54:10)
    at Array.forEach (native)
    at Client.reload (C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\client.js:52:9)
    at Server.<anonymous> (C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\server.js:179:12)
    at Array.map (native)
    at Server.changed (C:\dev\marketingsite\node_modules\grunt-contrib-watch\node_modules\tiny-lr\lib\server.js:176:43)
    at LR.trigger (C:\dev\marketingsite\node_modules\grunt-contrib-watch\tasks\lib\livereload.js:51:17)
    at TaskRun.complete (C:\dev\marketingsite\node_modules\grunt-contrib-watch\tasks\lib\taskrun.js:78:23)
    at C:\dev\marketingsite\node_modules\grunt-contrib-watch\tasks\lib\taskrunner.js:266:14
```

**Comment by jrobeson** [comment] 2015-06-10 23:08
Can folks still reproduce this?

**Comment by mklabs** [comment] 2015-06-14 11:55
Hello, sorry guys for not being very active on this issue the last two years :pensive: 

It looks like the ws handler is lost at some point in this configuration.

I'm closing the issue for now, feel free to reopen if it's still an issue for you. Also, if you have a github project with grunt and grunt contrib watch already setup, please paste the link. I'll see if I can reproduce it.

**Closed by mklabs** 2015-06-14 11:55 UTC
